deployment:
  replicas: 2
  image:
    repository: ghcr.io/rbren/vizzy
    tag: latest
  env:
  - name: STORAGE_STRATEGY
    value: local
  - name: LOCAL_STORAGE_PATH
    value: /storage

ingress:
  enabled: false

hpa:
  enabled: true
  min: 2
  max: 5
