apiVersion: v1
kind: Service
metadata:
  name: vizzy
  labels:
    app: vizzy
spec:
  ports:
  - name: server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vizzy
  type: ClusterIP
